# Generated by Django 4.0.2 on 2022-04-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_DoB',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_city',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_gender',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
