# Generated by Django 4.0.2 on 2022-03-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
