# Generated by Django 4.0.2 on 2022-05-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectBackend', '0002_remove_profile_profile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
