# Generated by Django 4.0.2 on 2022-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectBackend', '0005_games_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='year_of_release',
            field=models.IntegerField(),
        ),
    ]
