# Generated by Django 4.0.2 on 2022-04-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectBackend', '0006_alter_games_year_of_release'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
