# Generated by Django 4.0.2 on 2022-04-24 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectBackend', '0008_alter_game_developer_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='year_of_release',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
